#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Generate H.264 CABAC tables from the pinned FFmpeg upstream snapshot."""

from __future__ import annotations

import pathlib
import re
import textwrap


ROOT = pathlib.Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / ".upstream" / "ffmpeg-n8.0.1" / "libavcodec"
OUT = ROOT / "internal" / "h264" / "cabac_tables.go"


def strip_comments(src: str) -> str:
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    src = re.sub(r"//.*", "", src)
    return src


def find_array_body(src: str, decl: str) -> str:
    pos = src.index(decl)
    start = src.index("{", pos)
    depth = 0
    for i in range(start, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return src[start + 1 : i]
    raise RuntimeError(f"array body not closed: {decl}")


def ints(body: str) -> list[int]:
    return [int(x) for x in re.findall(r"-?\d+", strip_comments(body))]


def context_pairs(body: str) -> list[tuple[int, int]]:
    values = ints(body)
    if len(values) % 2 != 0:
        raise RuntimeError("odd number of context init entries")
    return [(values[i], values[i + 1]) for i in range(0, len(values), 2)]


def format_u8_array(name: str, values: list[int]) -> str:
    wrapped = [v & 0xFF for v in values]
    lines = [f"var {name} = [{len(wrapped)}]uint8{{"]
    for i in range(0, len(wrapped), 16):
        lines.append("\t" + ", ".join(str(v) for v in wrapped[i : i + 16]) + ",")
    lines.append("}")
    return "\n".join(lines)


def format_i8_pairs(name: str, pairs: list[tuple[int, int]]) -> str:
    lines = [f"var {name} = [{len(pairs)}][2]int8{{"]
    for i in range(0, len(pairs), 4):
        chunk = pairs[i : i + 4]
        lines.append("\t" + " ".join(f"{{{a}, {b}}}," for a, b in chunk))
    lines.append("}")
    return "\n".join(lines)


def format_pb(name: str, groups: list[list[tuple[int, int]]]) -> str:
    lines = [f"var {name} = [{len(groups)}][1024][2]int8{{"]
    for group in groups:
        lines.append("\t{")
        for i in range(0, len(group), 4):
            chunk = group[i : i + 4]
            lines.append("\t\t" + " ".join(f"{{{a}, {b}}}," for a, b in chunk))
        lines.append("\t},")
    lines.append("}")
    return "\n".join(lines)


def split_top_level_groups(body: str) -> list[str]:
    groups: list[str] = []
    depth = 0
    start: int | None = None
    for i, ch in enumerate(body):
        if ch == "{":
            if depth == 0:
                start = i + 1
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                groups.append(body[start:i])
                start = None
    return groups


def main() -> None:
    cabac_c = (UPSTREAM / "cabac.c").read_text()
    h264_cabac_c = (UPSTREAM / "h264_cabac.c").read_text()

    cabac_tables = ints(find_array_body(cabac_c, "ff_h264_cabac_tables"))
    if len(cabac_tables) != 512 + 4 * 2 * 64 + 4 * 64 + 63:
        raise RuntimeError(f"unexpected CABAC table length: {len(cabac_tables)}")

    init_i = context_pairs(find_array_body(h264_cabac_c, "cabac_context_init_I"))
    if len(init_i) != 1024:
        raise RuntimeError(f"unexpected I context length: {len(init_i)}")

    pb_body = find_array_body(h264_cabac_c, "cabac_context_init_PB")
    init_pb = [context_pairs(group) for group in split_top_level_groups(pb_body)]
    if len(init_pb) != 3 or any(len(group) != 1024 for group in init_pb):
        raise RuntimeError("unexpected PB context dimensions")

    out = "\n\n".join(
        [
            "// SPDX-License-Identifier: LGPL-2.1-or-later",
            "// Code generated by scripts/generate-cabac-tables.py from FFmpeg n8.0.1; DO NOT EDIT.",
            "package h264",
            format_u8_array("h264CABACTables", cabac_tables),
            format_i8_pairs("h264CABACContextInitI", init_i),
            format_pb("h264CABACContextInitPB", init_pb),
            "",
        ]
    )
    OUT.write_text(out)


if __name__ == "__main__":
    main()
