#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export GOH264_BENCH_ITERS="${GOH264_BENCH_ITERS:-1}"
export GOH264_BENCH_REPEATS="${GOH264_BENCH_REPEATS:-2}"
export GOH264_BENCH_WARMUP="${GOH264_BENCH_WARMUP:-1}"
export GOH264_BENCH_MAX_ENTRIES="${GOH264_BENCH_MAX_ENTRIES:-1}"
export GOH264_BENCH_MAX_GO_ALLOC_BYTES_PER_ITER="${GOH264_BENCH_MAX_GO_ALLOC_BYTES_PER_ITER:-64000000}"
export GOH264_BENCH_MAX_GO_ALLOCS_PER_ITER="${GOH264_BENCH_MAX_GO_ALLOCS_PER_ITER:-10000}"

filter="${GOH264_RELEASE_ALLOC_FILTER:-canl4}"
exec "$ROOT/scripts/h264-real-vector-bench.sh" "$filter" "$@"
